name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - pip
  - xeus-python
  - anywidget
  - requests
  - pandas
  - plotnine
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - folium
  - matplotlib
  - python-dateutil
  - requests-cache
  - scipy
  - pip:
    - jupyterlite-simple-cors-proxy
    - "fastf1 --no-deps"
    - timple>=0.1.6
    - ./packages/rapidfuzz-3.11.0-cp312-cp312-emscripten.whl